#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : secretstorage
Version  : 3.1.2
Release  : 34
URL      : file:///insilications/build/clearlinux/packages/secretstorage/secretstorage-3.1.2.zip
Source0  : file:///insilications/build/clearlinux/packages/secretstorage/secretstorage-3.1.2.zip
Summary  : Python bindings to FreeDesktop.org Secret Service API
Group    : Development/Tools
License  : GPL-2.0
Requires: secretstorage-python = %{version}-%{release}
Requires: secretstorage-python3 = %{version}-%{release}
Requires: cryptography
Requires: jeepney
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : findutils
BuildRequires : jeepney

%description
.. image:: https://api.travis-ci.org/mitya57/secretstorage.svg
:target: https://travis-ci.org/mitya57/secretstorage
:alt: Travis CI status
.. image:: https://codecov.io/gh/mitya57/secretstorage/branch/master/graph/badge.svg
:target: https://codecov.io/gh/mitya57/secretstorage
:alt: Coverage status
.. image:: https://readthedocs.org/projects/secretstorage/badge/?version=latest
:target: https://secretstorage.readthedocs.io/en/latest/
:alt: ReadTheDocs status

%package python
Summary: python components for the secretstorage package.
Group: Default
Requires: secretstorage-python3 = %{version}-%{release}

%description python
python components for the secretstorage package.


%package python3
Summary: python3 components for the secretstorage package.
Group: Default
Requires: python3-core
Provides: pypi(secretstorage)
Requires: pypi(cryptography)
Requires: pypi(jeepney)

%description python3
python3 components for the secretstorage package.


%prep
%setup -q -n secretstorage-3.1.2
cd %{_builddir}/secretstorage-3.1.2

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596636452
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
